### ISSUE TITLE
does scanner_refl_fix support arbitrary source gamma?

### ISSUE THREAD

**Issue by jparanada** [doug3236/scanner_refl_fix#1]
My current scanning workflow starts with "raw" scans that are linear light-encoded (i.e. if gamma of 1.8 were applied to the image it would look "normal"; currently it looks dark).

My question is: does scanner_refl_fix (srf) behave correctly if a linear light scan of scan_calibration.tif is given to it? Ideally I'd like to use the resulting scanner_cal.txt to srf-process a linear light scan of an IT8 target and use the output to create some profile scanner_profile_for_srf.icc.  Then I'd use srf on my various linear light scans to create image1_f.tif, image2_f.tif, and apply scanner_profile_for_srf.icc to those images.

Or do I first have to apply gamma 1.8 to all my scans (including the scan_calibration.tif scan) before processing with srf for its calculations to be done correctly?

**Comment by doug3236** [comment]
Yes, it works with arbitrary gamma. It measures gamma as part of the initial calibration process and saves that along with the reflection matrix in the calibration file so it should work ok even with gamma=1. The measured gamma isn't critical and can be off +- 20% without much effect as it's a secondary factor. It measures the calibration chart, which should be printed using Rel Col and uses the gray patches from which it calculates gamma. The program internally then converts the image to gamma=1 to do processing then back to it's original gamma.
