### ISSUE TITLE
which way of invoking scanner_refl_fix -c is most accurate?

### ISSUE THREAD

**Issue by jparanada** [doug3236/scanner_refl_fix#3]
`scanner_refl_fix -c` can be invoked 3 ways:
1. with only the tif as input (auto-calculates gamma)
2. with a single additional arg, which is assumed to be "gamma".
3. with passed-in Y values, measured from the printed chart with a spectrophotometer

A couple of questions:
* For method 2, is this gamma supposed to correspond to the gamma correction that's been applied to the image during scanning? i.e. if I know that my scanning software applies a gamma of 2.2 (but I've turned off all other adjustments so the image is otherwise "raw"), would I enter "2.2" here?
* Which of these three methods is expected to be the most accurate?

**Comment by doug3236** [comment]
Gamma is normally auto calculated from the group of small neutral patches. The program assumes that the scanner's gamma is constant. I've found some variation on the Epson V850 depending on the reflectance level with it slightly increasing with more reflective patches. However, errors (up to +-20%) in gamma have relatively small effects. Especially if one uses the gamma at the brighter end which the auto version does. As reflected light decreases, the impact of gamma error also decreases in proportion. The option is provided in case someone has a specialized application and is trying to tune things for a specific application. Such as scanning something with a small reflectance range that has a very bright surround and they need very high accuracy. Here, a spectrophotometer and a bit of experimenting can improve re-reflectance errors somewhat. But the auto mode is what I use. It's a pretty large improvement.

**Comment by doug3236** [comment]
The software will automatically detect the scanned image gamma. It's important to use the same scanning mode to scan the chart to create the reflectance grid that you use when scanning images.
