### ISSUE TITLE
"Vector too long" message after trying to run calibration

### ISSUE THREAD

**Issue by electro-soup** [doug3236/scanner_refl_fix#4]
I wanted to try your tool, I do all neccessary thing per instruction, but only I am getting while trying to create correction file using scanned image and -c option is message from the title. What the cause can be, maybe I am doing something wrong, maybe this is the quality of print or scan? Please see my attached scan
[native.zip](https://github.com/doug3236/scanner_refl_fix/files/7460600/native.zip)

**Comment by doug3236** [comment]
Please identify the scanner make and model you are using. An initial look at the image shows very little re-reflection error. Very different from the Epson V850 series.

I'm able to reproduce the error. I appreciate you posting the scan.
I will be looking at the error cause and update what I find.

You might try cropping the scan with white border. on all sides The program currently assumes a white border in order to align the image. In processing, the white border is not used but its partial absence may be an issue since it may fail to align as it sees some but not all, of the border.

**Comment by doug3236** [comment]
Both the print and the scan must be dimensionally correct. The original image has a large white square at the top. It is exactly 3 inches on a side, It's critical that this is printed so the square in the print is also 3 inches on a side. Then, when you scan it and measure the square it will also be 3 inches on a side. The scan doesn't have to be 200 DPI and can be larger but the calculations are based on the scan size being at 100% and not shrunk or enlarged.

**Comment by electro-soup** [comment]
Thank you for your suggestions - I was wondering if this is connected with cropping and sizes of the images itself, I will try to adjust my scans and try again. The image was printed on a regular A4 sheet (non glossy). The scanner model I use is Microtek 1000XL Plus (A3 bed scanner)

**Comment by doug3236** [comment]
I took a closer look at the image you posted. The tif file was tagged as 120 DPI. I changed that to 200 DPI and the dimensions are closer but still off 5% or so.

Also took a look in Photoshop using ctrl-m (curves) to explore the image. It has some really unusual artifacts. It's really very noisy and the 3" white square is significantly darker horizontally across the middle than nearer the top or bottom. And when the black areas are examined, there are strange ghost type images that are darker versions of the white squares above. I suspect the scanner needs a good cleaning in addition to the other issues.

**Comment by electro-soup** [comment]
Maybe issues you described is connected with very poor print... I made one sample from photo lab on glossy paper, unfortunetaly it is cropped and small, but I will post it anyway for research purpose:)
[glossy_crop.zip](https://github.com/doug3236/scanner_refl_fix/files/7528152/glossy_crop.zip)

**Comment by doug3236** [comment]
That image does look much better even if too small. It does show the re-reflection pattern which the utility can correct. However, there is an odd brighter, thin vertical line on the right side of the gray boxes. Looks like some sort of scanner artifact if it's no on the print. Do you have an inkjet or laser printer you can print a full size image on? It needs a full size to properly calibrate.

**Comment by electro-soup** [comment]
I checked the image - this brighter line is also na on print. I printed this image in self-service photolab, it appears that prints only "decent" quality. Yeah, I have a laser printer, but I could not get satisfying print from it (as you could see on first picture I attached). I checked different settings to get 100% correct print, I used Adobe print utility, but with no success (still this vector too long error). I will check it again maybe in next weeks, for now I have no time for this:)
